name: CI â€” Build & Push to ECR (and optional ECS deploy)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPO: ${{ secrets.ECR_REPOSITORY }}
      ACOOUNT: 642916324385.dkr.ecr.us-east-1.amazonaws.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Ensure ECR repository exists
      #   run: |
      #     ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      #     ECR_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}"
      #     echo "ECR_URI=${ECR_URI}" >> $GITHUB_OUTPUT
      #     if ! aws ecr describe-repositories --repository-names "${ECR_REPO}" >/dev/null 2>&1; then
      #       echo "Creating ECR repository ${ECR_REPO}"
      #       aws ecr create-repository --repository-name "${ECR_REPO}" --image-scanning-configuration scanOnPush=true
      #     else
      #       echo "Repository ${ECR_REPO} already exists"
      #     fi

      - name: Build & push Docker image to ECR
        run: |
          docker build -f Dockerfile -t ${ECR_REPO}/aws_api:latest .
          echo "Pusing the image to ${ECR_REPO}/${{ inputs.ecr-repo-name }}:${{ inputs.image-tag }}"
          docker push 642916324385.dkr.ecr.ap-southeast-1.amazonaws.com/${ECR_REPO}/aws_api:latest